.\" Process this file with
.\" groff -man -Tascii getifaddrs.1
.\"
.\" http://www.schweikhardt.net/man_page_howto.html
.\" Gosh, man pages are ugly...
.TH GETIFADDRS 1 "JULY 2014" "Josh Oldenburg" "Josh's Utilities"
.SH NAME
getifaddrs \- get IP addresses, in a parseable format
.SH SYNOPSIS
.B getifaddrs [-q] [
.I interface
.B ]
.SH DESCRIPTION
.B getifaddrs
outputs the IP addresses for the system. It shows all
interfaces by default. Internally, it uses
.BR getifaddrs (3)
to get the addresses. Passing a nonexistant interface
does not error but does not output anything.
.SH OPTIONS
.IP -q
Output only the addresses
.IP interface
Display only the address(es) of the specified interface.
.SH BUGS
None? Is that even possible? Surely someone will find something.
Please report bugs at https://github.com/JoshTheGeek/ipaddrutil
.SH AUTHOR
Josh Oldenburg @ http://joshuaoldenburg.com

https://github.com/JoshTheGeek/ipaddrutil
.SH "SEE ALSO"
.BR getifaddrs (3),
.BR ifconfig (1)
